name: ongkirapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: 3.1.11
  connectivity_plus: ^2.2.1
  cupertino_icons: ^1.0.2
  dropdown_search: 0.6.3
  firebase_auth: 3.3.12
  firebase_core: 1.14.0
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  get: 4.3.8
  google_sign_in: 5.2.4
  http: 0.13.3
  lottie: ^1.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: launcher_icon
  image_path: assets/icon/icon.png
  ios: true

flutter:
  assets:
    - assets/images/
  uses-material-design: true
